experiment:
  data_config:
    strategy: fixed
    dataloader: VisualLoader
    dataset_path: ../data/{0}/trainingset.tsv
    train_path: ../data/{0}/trainingset.tsv
    validation_path: ../data/{0}/validationset.tsv
    test_path: ../data/{0}/testset.tsv
    side_information:
      visual_features: ../data/{0}/original/cnn_features_resnet50_avg_pool/
      visual_pca_features: ../data/{0}/original/cnn_features_resnet50_avg_pool_pca128/
      visual_feat_map_features: ../data/{0}/original/cnn_features_resnet50_conv5_block3_out/
      item_mapping: ../data/{0}/visual_feats.tsv
  dataset: amazon_boys_girls_resnet50
  top_k: 100
  evaluation:
    cutoffs: [ 10, 50, 100 ]
    simple_metrics: [ Precision, Recall, AUC, HR, F1, MRR, MAP, ItemCoverage, Gini, EFD, EPC, ACLT, APLT, ARP ]
    relevance_threshold: 1
    paired_ttest: True
  gpu: -1
  models:
    VBPR:
      meta:
        hyper_opt_alg: grid
        validation_rate: 15
        verbose: True
        save_weights: True
        save_recs: True
        validation_metric: AUC
        restore_epoch: -1
      lr: [ 0.0001, 0.001, 0.01 ]
      epochs: 300
      factors: [ 32, 64, 128 ]
      factors_d: 20
      batch_size: 256
      l_w: [ 0.00001, 0.001, 0 ]
      l_b: 0
      l_e: [ 0.00001, 0.001, 0 ]
    DeepStyle:
      meta:
        hyper_opt_alg: grid
        validation_rate: 15
        verbose: True
        save_weights: True
        save_recs: True
        validation_metric: AUC
        restore_epoch: -1
      lr: [ 0.0001, 0.001, 0.01 ]
      epochs: 300
      factors: [ 32, 64, 128 ]
      batch_size: 256
      l_w: [ 0.00001, 0.001, 0 ]
    ACF:
      meta:
        hyper_opt_alg: grid
        validation_rate: 15
        verbose: True
        save_weights: True
        save_recs: True
        validation_metric: AUC
        restore_epoch: -1
      lr: [ 0.0001, 0.001, 0.01 ]
      epochs: 300
      factors: [ 32, 64, 128 ]
      batch_size: 256
      l_w: [ 0.00001, 0.001, 0 ]
      layers_component: (64, 1)
      layers_item: (64, 1)
    VNPR:
      meta:
        hyper_opt_alg: grid
        validation_rate: 15
        verbose: True
        save_weights: True
        save_recs: True
        validation_metric: AUC
        restore_epoch: -1
      lr: [ 0.0001, 0.001, 0.01 ]
      epochs: 300
      mf_factors: [ 32, 64, 128 ]
      batch_size: 256
      mlp_hidden_size: (128, 64, 1)
      prob_keep_dropout: [ 0.4, 0.6 ]
      l_w: [ 0.00001, 0.001, 0 ]
      l_v: [ 0.00001, 0.001, 0 ]